// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillTrax.Models;

namespace SkillTrax.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20180713191209_ModelsUpdate")]
    partial class ModelsUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SkillTrax.Models.Certification", b =>
                {
                    b.Property<int>("CertificationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CertCategoryId");

                    b.Property<string>("CertificationName")
                        .IsRequired();

                    b.HasKey("CertificationId");

                    b.HasIndex("CertCategoryId");

                    b.ToTable("Certification");
                });

            modelBuilder.Entity("SkillTrax.Models.CertificationCategory", b =>
                {
                    b.Property<int>("CertCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CertCategoryName")
                        .IsRequired();

                    b.HasKey("CertCategoryId");

                    b.ToTable("CertificationCategory");
                });

            modelBuilder.Entity("SkillTrax.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdUniqueIdentifier");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<bool>("IsAdmin");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<int?>("RoleTypeRoleId");

                    b.HasKey("EmployeeId");

                    b.HasIndex("RoleTypeRoleId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("SkillTrax.Models.EmployeeCertification", b =>
                {
                    b.Property<int>("EmployeeId");

                    b.Property<int>("CertificationId");

                    b.HasKey("EmployeeId", "CertificationId");

                    b.HasIndex("CertificationId");

                    b.ToTable("EmployeeCertification");
                });

            modelBuilder.Entity("SkillTrax.Models.EmployeeSkill", b =>
                {
                    b.Property<int>("SkillId");

                    b.Property<int>("EmployeeId");

                    b.HasKey("SkillId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeSkill");
                });

            modelBuilder.Entity("SkillTrax.Models.RoleType", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleName")
                        .IsRequired();

                    b.HasKey("RoleId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("SkillTrax.Models.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SkillName")
                        .IsRequired();

                    b.HasKey("SkillId");

                    b.ToTable("Skill");
                });

            modelBuilder.Entity("SkillTrax.Models.SkillType", b =>
                {
                    b.Property<int>("SkillTypeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SkillTypeName")
                        .IsRequired();

                    b.HasKey("SkillTypeId");

                    b.ToTable("SkillType");
                });

            modelBuilder.Entity("SkillTrax.Models.SkillTypeSkill", b =>
                {
                    b.Property<int>("SkillId");

                    b.Property<int>("SkillTypeId");

                    b.HasKey("SkillId", "SkillTypeId");

                    b.HasIndex("SkillTypeId");

                    b.ToTable("SkillTypeSkill");
                });

            modelBuilder.Entity("SkillTrax.Models.Solution", b =>
                {
                    b.Property<int>("SolutionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SolutionName")
                        .IsRequired();

                    b.HasKey("SolutionId");

                    b.ToTable("Solution");
                });

            modelBuilder.Entity("SkillTrax.Models.SolutionSkill", b =>
                {
                    b.Property<int>("SkillId");

                    b.Property<int>("SolutionId");

                    b.HasKey("SkillId", "SolutionId");

                    b.HasIndex("SolutionId");

                    b.ToTable("SolutionSkill");
                });

            modelBuilder.Entity("SkillTrax.Models.Certification", b =>
                {
                    b.HasOne("SkillTrax.Models.CertificationCategory", "CertCategory")
                        .WithMany("Certifications")
                        .HasForeignKey("CertCategoryId");
                });

            modelBuilder.Entity("SkillTrax.Models.Employee", b =>
                {
                    b.HasOne("SkillTrax.Models.RoleType", "RoleType")
                        .WithMany("Employees")
                        .HasForeignKey("RoleTypeRoleId");
                });

            modelBuilder.Entity("SkillTrax.Models.EmployeeCertification", b =>
                {
                    b.HasOne("SkillTrax.Models.Certification", "Certification")
                        .WithMany("EmployeeCertifications")
                        .HasForeignKey("CertificationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SkillTrax.Models.Employee", "Employee")
                        .WithMany("EmployeeCertifications")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SkillTrax.Models.EmployeeSkill", b =>
                {
                    b.HasOne("SkillTrax.Models.Employee", "Employee")
                        .WithMany("EmployeeSkills")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SkillTrax.Models.Skill", "Skill")
                        .WithMany("EmployeeSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SkillTrax.Models.SkillTypeSkill", b =>
                {
                    b.HasOne("SkillTrax.Models.Skill", "Skill")
                        .WithMany("SkillTypeSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SkillTrax.Models.SkillType", "SkillType")
                        .WithMany("SkillTypeSkills")
                        .HasForeignKey("SkillTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SkillTrax.Models.SolutionSkill", b =>
                {
                    b.HasOne("SkillTrax.Models.Skill", "Skill")
                        .WithMany("SolutionSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SkillTrax.Models.Solution", "Solution")
                        .WithMany("SolutionSkills")
                        .HasForeignKey("SolutionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
